version: "3.6"
services:
  hasura-cli-console:
    build: ./.docker-images/hasura-cli
    ports:
      - 9695:9695
    volumes:
      - ./hasura-state:/project
    command: >
      hasura console 
        --log-level DEBUG 
        --address "hasura-cli-console" 
        --no-browser 
        --api-host https://${CODESPACE_NAME}-9693.preview.app.github.dev
        --api-port 443
        --endpoint https://${CODESPACE_NAME}-8080.preview.app.github.dev
        --admin-secret ${HASURA_ADMIN_SECRET:-}
    working_dir: /project
    restart: unless-stopped
    depends_on:
      hasura-engine:
        condition: service_healthy
    networks:
      - hasura

  hasura-cli-api:
    build: ./.docker-images/hasura-cli
    ports:
      - 9693:9693
    volumes:
      - ./hasura-state:/project
    command: >
      hasura console
        --log-level DEBUG
        --address "hasura-cli-api"
        --no-browser
        --endpoint http://hasura-engine:8080
        --admin-secret ${HASURA_ADMIN_SECRET:-}
    working_dir: /project
    restart: unless-stopped
    depends_on:
      hasura-engine:
        condition: service_healthy
    networks:
      - hasura
